import type { Constellation } from './types'

export const CONSTELLATIONS: Constellation[] = [
  {
    id: 'aries',
    name: 'Aries',
    latinName: 'Aries',
    zodiacSign: 'Aries',
    description: 'The Ram — a constellation of the zodiac representing the golden fleece in Greek mythology.',
    distance: '~79 light-years (Hamal)',
    mainStars: ['Hamal', 'Sheratan', 'Mesarthim'],
    visibilitySeason: 'Best seen in December',
    stars: [
      { x: -2, y: 1, z: -10, brightness: 1 },
      { x: -1, y: 0.5, z: -10, brightness: 0.7 },
      { x: 0, y: 0, z: -10, brightness: 0.5 },
      { x: 1, y: -0.3, z: -10, brightness: 0.6 },
    ],
    lines: [[0, 1], [1, 2], [2, 3]],
  },
  {
    id: 'taurus',
    name: 'Taurus',
    latinName: 'Taurus',
    zodiacSign: 'Taurus',
    description: 'The Bull — home to the Pleiades star cluster and the red giant Aldebaran.',
    distance: '~65 light-years (Aldebaran)',
    mainStars: ['Aldebaran', 'Elnath', 'Alcyone'],
    visibilitySeason: 'Best seen in January',
    stars: [
      { x: -3, y: 0, z: -10, brightness: 1 },
      { x: -1.5, y: 1, z: -10, brightness: 0.8 },
      { x: 0, y: 0.5, z: -10, brightness: 0.9 },
      { x: 1.5, y: 0, z: -10, brightness: 0.7 },
      { x: 3, y: -0.5, z: -10, brightness: 0.6 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4]],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    latinName: 'Gemini',
    zodiacSign: 'Gemini',
    description: 'The Twins — Castor and Pollux, two bright stars representing the mythological twins.',
    distance: '~33 light-years (Pollux)',
    mainStars: ['Castor', 'Pollux', 'Alhena'],
    visibilitySeason: 'Best seen in February',
    stars: [
      { x: -1, y: 2, z: -10, brightness: 0.9 },
      { x: -1, y: 0, z: -10, brightness: 1 },
      { x: 1, y: 0, z: -10, brightness: 0.95 },
      { x: 1, y: 2, z: -10, brightness: 0.85 },
      { x: 0, y: -1, z: -10, brightness: 0.6 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [1, 4], [2, 4]],
  },
  {
    id: 'cancer',
    name: 'Cancer',
    latinName: 'Cancer',
    zodiacSign: 'Cancer',
    description: 'The Crab — a faint zodiac constellation, home to the Beehive Cluster (M44).',
    distance: '~131 light-years (Acubens)',
    mainStars: ['Acubens', 'Altarf', 'Asellus Australis'],
    visibilitySeason: 'Best seen in March',
    stars: [
      { x: -1.5, y: 0.5, z: -10, brightness: 0.5 },
      { x: 0, y: 1, z: -10, brightness: 0.6 },
      { x: 1.5, y: 0.5, z: -10, brightness: 0.5 },
      { x: 0, y: -0.5, z: -10, brightness: 0.4 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 0]],
  },
  {
    id: 'leo',
    name: 'Leo',
    latinName: 'Leo',
    zodiacSign: 'Leo',
    description: 'The Lion — one of the most recognizable constellations, featuring the bright star Regulus.',
    distance: '~79 light-years (Regulus)',
    mainStars: ['Regulus', 'Denebola', 'Algieba'],
    visibilitySeason: 'Best seen in April',
    stars: [
      { x: -2, y: 0, z: -10, brightness: 1 },
      { x: -1, y: 1, z: -10, brightness: 0.7 },
      { x: 0, y: 1.2, z: -10, brightness: 0.8 },
      { x: 1, y: 0.5, z: -10, brightness: 0.75 },
      { x: 2, y: -0.5, z: -10, brightness: 0.85 },
      { x: 3, y: -1, z: -10, brightness: 0.9 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]],
  },
  {
    id: 'virgo',
    name: 'Virgo',
    latinName: 'Virgo',
    zodiacSign: 'Virgo',
    description: 'The Maiden — the largest zodiac constellation, containing the bright star Spica.',
    distance: '~250 light-years (Spica)',
    mainStars: ['Spica', 'Porrima', 'Vindemiatrix'],
    visibilitySeason: 'Best seen in May',
    stars: [
      { x: 0, y: -1.5, z: -10, brightness: 1 },
      { x: -1, y: 0, z: -10, brightness: 0.7 },
      { x: 0, y: 0.5, z: -10, brightness: 0.6 },
      { x: 1, y: 1, z: -10, brightness: 0.65 },
      { x: 2, y: 0.5, z: -10, brightness: 0.55 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4]],
  },
  {
    id: 'libra',
    name: 'Libra',
    latinName: 'Libra',
    zodiacSign: 'Libra',
    description: 'The Scales — representing balance and justice, the only zodiac constellation depicting an object.',
    distance: '~185 light-years (Zubeneschamali)',
    mainStars: ['Zubeneschamali', 'Zubenelgenubi', 'Brachium'],
    visibilitySeason: 'Best seen in June',
    stars: [
      { x: -1.5, y: 0, z: -10, brightness: 0.7 },
      { x: -0.5, y: 0.5, z: -10, brightness: 0.6 },
      { x: 0.5, y: 0.5, z: -10, brightness: 0.6 },
      { x: 1.5, y: 0, z: -10, brightness: 0.65 },
    ],
    lines: [[0, 1], [1, 2], [2, 3]],
  },
  {
    id: 'scorpius',
    name: 'Scorpius',
    latinName: 'Scorpius',
    zodiacSign: 'Scorpio',
    description: 'The Scorpion — featuring Antares, a red supergiant and one of the brightest stars in the night sky.',
    distance: '~550 light-years (Antares)',
    mainStars: ['Antares', 'Shaula', 'Sargas'],
    visibilitySeason: 'Best seen in July',
    stars: [
      { x: -2, y: 0, z: -10, brightness: 1 },
      { x: -1, y: -0.5, z: -10, brightness: 0.7 },
      { x: 0, y: -1, z: -10, brightness: 0.75 },
      { x: 1, y: -0.5, z: -10, brightness: 0.8 },
      { x: 2, y: 0, z: -10, brightness: 0.85 },
      { x: 3, y: 0.5, z: -10, brightness: 0.9 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]],
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    latinName: 'Sagittarius',
    zodiacSign: 'Sagittarius',
    description: 'The Archer — points toward the center of the Milky Way galaxy.',
    distance: '~78 light-years (Kaus Australis)',
    mainStars: ['Kaus Australis', 'Nunki', 'Ascella'],
    visibilitySeason: 'Best seen in August',
    stars: [
      { x: 0, y: 0, z: -10, brightness: 0.9 },
      { x: -1, y: 1, z: -10, brightness: 0.7 },
      { x: 1, y: 1, z: -10, brightness: 0.7 },
      { x: -0.5, y: 2, z: -10, brightness: 0.6 },
      { x: 0.5, y: 2, z: -10, brightness: 0.6 },
    ],
    lines: [[0, 1], [0, 2], [1, 3], [2, 4], [3, 4]],
  },
  {
    id: 'capricornus',
    name: 'Capricornus',
    latinName: 'Capricornus',
    zodiacSign: 'Capricorn',
    description: 'The Sea Goat — a faint constellation representing a creature from ancient mythology.',
    distance: '~109 light-years (Deneb Algedi)',
    mainStars: ['Deneb Algedi', 'Dabih', 'Alshat'],
    visibilitySeason: 'Best seen in September',
    stars: [
      { x: -1.5, y: 0.5, z: -10, brightness: 0.6 },
      { x: -0.5, y: 0, z: -10, brightness: 0.5 },
      { x: 0.5, y: 0, z: -10, brightness: 0.55 },
      { x: 1.5, y: 0.5, z: -10, brightness: 0.65 },
    ],
    lines: [[0, 1], [1, 2], [2, 3]],
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    latinName: 'Aquarius',
    zodiacSign: 'Aquarius',
    description: 'The Water Bearer — a large but faint constellation best known for meteor showers.',
    distance: '~540 light-years (Sadalsuud)',
    mainStars: ['Sadalsuud', 'Sadalmelik', 'Skat'],
    visibilitySeason: 'Best seen in October',
    stars: [
      { x: -1, y: 1, z: -10, brightness: 0.7 },
      { x: 0, y: 0.5, z: -10, brightness: 0.75 },
      { x: 1, y: 0, z: -10, brightness: 0.65 },
      { x: 0, y: -0.5, z: -10, brightness: 0.6 },
      { x: 1, y: -1, z: -10, brightness: 0.55 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4]],
  },
  {
    id: 'pisces',
    name: 'Pisces',
    latinName: 'Pisces',
    zodiacSign: 'Pisces',
    description: 'The Fish — two fish tied together, representing Venus and Cupid in Greek mythology.',
    distance: '~294 light-years (Alrescha)',
    mainStars: ['Alrescha', 'Alpherg', 'Torcular'],
    visibilitySeason: 'Best seen in November',
    stars: [
      { x: -2, y: 0.5, z: -10, brightness: 0.6 },
      { x: -1, y: 0, z: -10, brightness: 0.5 },
      { x: 0, y: 0.5, z: -10, brightness: 0.7 },
      { x: 1, y: 0, z: -10, brightness: 0.5 },
      { x: 2, y: 0.5, z: -10, brightness: 0.55 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4]],
  },
  {
    id: 'orion',
    name: 'Orion',
    latinName: 'Orion',
    description: 'The Hunter — one of the most prominent constellations, visible worldwide.',
    distance: '~642 light-years (Rigel)',
    mainStars: ['Betelgeuse', 'Rigel', 'Bellatrix', 'Mintaka'],
    visibilitySeason: 'Best seen in January',
    stars: [
      { x: -1.5, y: 2, z: -10, brightness: 0.9 },
      { x: 1.5, y: 2, z: -10, brightness: 0.85 },
      { x: -1, y: 0.5, z: -10, brightness: 0.7 },
      { x: 0, y: 0.5, z: -10, brightness: 0.75 },
      { x: 1, y: 0.5, z: -10, brightness: 0.7 },
      { x: -1.5, y: -1, z: -10, brightness: 1 },
      { x: 1.5, y: -1, z: -10, brightness: 1 },
    ],
    lines: [[0, 2], [2, 3], [3, 4], [4, 1], [0, 5], [1, 6], [5, 6]],
  },
  {
    id: 'ursa-major',
    name: 'Ursa Major',
    latinName: 'Ursa Major',
    description: 'The Great Bear — contains the Big Dipper asterism, used for navigation.',
    distance: '~123 light-years (Dubhe)',
    mainStars: ['Dubhe', 'Merak', 'Phecda', 'Megrez', 'Alioth', 'Mizar', 'Alkaid'],
    visibilitySeason: 'Best seen year-round (Northern Hemisphere)',
    stars: [
      { x: -3, y: 1, z: -10, brightness: 0.9 },
      { x: -2, y: 1.2, z: -10, brightness: 0.7 },
      { x: -1, y: 1, z: -10, brightness: 0.75 },
      { x: 0, y: 0.8, z: -10, brightness: 0.6 },
      { x: 1, y: 0.5, z: -10, brightness: 0.85 },
      { x: 2, y: 0.3, z: -10, brightness: 0.8 },
      { x: 3, y: 0, z: -10, brightness: 0.9 },
    ],
    lines: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6]],
  },
]

export function getConstellationById(id: string): Constellation | undefined {
  return CONSTELLATIONS.find((c) => c.id === id)
}
